### ISSUE TITLE
how to apply filters

### ISSUE THREAD

**Issue by grzanka** [yaptide/converter#175]
In UI user can define filters. We could add them in Fluka at least for Fluence scoring.

Fluence -> thats easy, you specify generalized particle.
For dose -> use AUXSCORE ?

When using AUXSCORE you can check if in the JSON coming from UI you have Z and A defined.

![image](https://github.com/yaptide/converter/assets/7374733/9e9d6a4a-5f3d-4ea1-a0a2-965627a341db)
![image](https://github.com/yaptide/converter/assets/7374733/8aaa83f9-452a-44aa-9e81-279fcca19df8)

**Comment by hendzeld** [comment]
`
Fluence -> thats easy, you specify generalized particle.
For dose -> use AUXSCORE ?
`
Is this comment current?
Now in UI, in case of SHIELDHIT we have filters for particles and DOSE does not have a filter:
Example:

```
Filter
    Name Primaries
    Z == 1
    A == 1
    GEN == 0
Filter
    Name Secondary_protons
    Z == 1
    A == 1
    GEN >= 1

Output
    Filename z_profile.bdo
    Geo CylZ_Mesh
    Quantity Dose  
    Quantity Fluence Protons 
    Quantity Fluence Primaries 
    Quantity Fluence Secondary_protons 

Output
    Filename yz_profile.bdo
    Geo YZ_Mesh
    Quantity Dose  
    Quantity Fluence Protons 
```

Additionally, according to this file we have filters like: `Primaries` and `Secondary_protons`.
Which can then be applied to generate multiple data sets in a single output file.
```
    Quantity Dose  
    Quantity Fluence Protons 
    Quantity Fluence Primaries 
    Quantity Fluence Secondary_protons 
```

![Image](https://github.com/yaptide/converter/assets/128628266/adda7e8e-2f9d-4885-964e-f4c7a7db6524)

In Shieldhit, we can define geometry once, and use it with SCORING (Dose) and multiple filters
In Fluka, AUXSCORE works as a replacement for SCORING in e.g. USRBIN.
Therefore, to get the same result in FLUKA, we must prepare one DOSE and three USRBIN scoring cards and additional filters.

Additionally, AUXSCORE can filter range or single scoring card.
Therefore, to apply one filter to N scoring from M, it will require N AUXSCORE cards.

Maybe I am missing something.

**Comment by hendzeld** [comment]
We can group filters and `DOSE` in a simple output unit.
By using something like this:
```
USRBIN           10.    ENERGY      -25.        5.        5.       2.9dose_xy
USRBIN           -5.       -5.       2.8      500.      500.        1. &
***
*** BELOW ARE AUXSCORE FILTERS FOR SCORING ABOVE
***
*** ALL PARTICLES
USRBIN           10.    ENERGY      -25.        5.        5.       2.9dose_xyf1
USRBIN           -5.       -5.       2.8      500.      500.        1. &
AUXSCORE      USRBIN  ALL-PART          dose_xyf1  dose_xyf1         1AMB74
***(A=12) e.g. CARBON
USRBIN           10.    ENERGY      -25.        5.        5.       2.9dose_xyf2
USRBIN           -5.       -5.       2.8      500.      500.        1. &
AUXSCORE      USRBIN    -1.2e6          dose_xyf2  dose_xyf2         1AMB74
***(Z=2) HELIUM
USRBIN           10.    ENERGY      -25.        5.        5.       2.9dose_xyf3
USRBIN           -5.       -5.       2.8      500.      500.        1. &
AUXSCORE      USRBIN     -200.          dose_xyf3  dose_xyf3         1AMB74
```

This will generate a single output with ENERGY and three additional filters.


![Image](https://github.com/yaptide/converter/assets/128628266/bfe6e327-9e73-4c17-8176-4544bd923f23)

The example above is not the best, but it shows that it will be important to remember to use `DOSE` as pymchelper will use whatever was specified in `USRBIN`. Therefore, despite calculating a dose it shows an energy.

Updated input which uses `DOSE` instead:
![Image](https://github.com/yaptide/converter/assets/128628266/b76a072a-1269-487e-bd88-a74470aed8a9)
